------------------------------------------------------------------------------
--                                                                          --
--                              Couverture                                  --
--                                                                          --
--                     Copyright (C) 2008-2009, AdaCore                     --
--                                                                          --
-- Couverture is free software; you can redistribute it  and/or modify it   --
-- under terms of the GNU General Public License as published by the Free   --
-- Software Foundation; either version 2, or (at your option) any later     --
-- version.  Couverture is distributed in the hope that it will be useful,  --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write  to  the Free  Software  Foundation,  59 Temple Place - Suite 330, --
-- Boston, MA 02111-1307, USA.                                              --
--                                                                          --
------------------------------------------------------------------------------
with Interfaces; use Interfaces;

package Qemu_Traces is

   -----------------------
   -- Trace file header --
   -----------------------

   --  Must be kept consistent with the C version in qemu-traces.h

   subtype Magic_String is String (1 .. 12);

   Qemu_Trace_Magic : constant Magic_String := "#QEMU-Traces";
   --  Expected value of the Magic field.

   Qemu_Trace_Version : constant Unsigned_8 := 1;
   --  Current version

   type Trace_Kind is (Raw, History, Info, Decision_Map, Consolidated);
   for Trace_Kind use
     (Raw          =>   0,
      History      =>   1,
      Info         =>   2,
      Decision_Map =>   3,
      Consolidated => 248);
   for Trace_Kind'Size use 8;
   --  Raw and history files are the one generated by Qemu.
   --  Decision Maps are generated by Xcov to control trace collection.
   --  Info is a special section that is followed by a standard trace section.
   --  The header fields after Kind (but big_endian) should be 0.
   --  The header is followed by Trace_Info records.

   --  What is Consolidated???

   type Trace_Header is record
      Magic : Magic_String;
      --  Magic string

      Version : Unsigned_8;
      --  Version of file format

      Kind : Trace_Kind;
      --  File kind

      Sizeof_Target_Pc : Unsigned_8;
      --  Size (in bytes) of program counter on target

      Big_Endian : Boolean;
      --  True if the host is big endian

      Machine_Hi : Unsigned_8;
      Machine_Lo : Unsigned_8;
      --  Target ELF machine ID

      Padding : Unsigned_16;
      --  Reserved, must be set to 0
   end record;

   --  If the file kind is Consolidated the common header is followed by this
   --  additional header.
   --  This header may be followed by 1 to 3 bytes of pads so that the traces
   --  are aligned on 4 bytes.

   type Trace_Header_Consolidated is record
      Length : Unsigned_32;
      --  Length of meta-data (using host endianness).
      --  Meta-data are just a raw stream of bytes (human readable text
      --  is expected).
   end record;

   type Info_Kind_Type is
     (Info_End, Exec_File_Name, Coverage_Options, User_Data, Date_Time);

   type Trace_Info_Header is record
      Info_Kind   : Unsigned_32;
      --  Info_Kind_Type'Pos, in endianness indicated by file header

      Info_Length : Unsigned_32;
      --  Length of associated data (must be 0 for Info_End)

   end record;
   --  An info section is composed of one ore more TLV fields.  The last one
   --  must be End.
   --  Length is the raw length of the data.  But it is always padded to 4
   --  bytes so that the next field is aligned on 4 bytes.

   Trace_Info_Alignment : constant := 4;

   type Trace_Info_Date is record
      Year  : Unsigned_16;
      Month : Unsigned_8;   --  1 .. 12
      Day   : Unsigned_8;   --  1 .. 31
      Hour  : Unsigned_8;   --  0 .. 23
      Min   : Unsigned_8;   --  0 .. 59
      Sec   : Unsigned_8;   --  0 .. 59
      Pad   : Unsigned_8;   --  0
   end record;

   --  Standard 64 and 32bits trace entries.
   type Trace_Entry64 is record
      Pc   : Unsigned_64;
      Size : Unsigned_16;
      Op   : Unsigned_8;
      Pad0 : Unsigned_8;
      Pad1 : Unsigned_32;
   end record;

   type Trace_Entry32 is record
      Pc   : Unsigned_32;
      Size : Unsigned_16;
      Op   : Unsigned_8;
      Pad0 : Unsigned_8;
   end record;

   --  _BLOCK means pc .. pc+size-1 was executed.
   Trace_Op_Block : constant Unsigned_8 := 16#10#;
   Trace_Op_Fault : constant Unsigned_8 := 16#20#;
   Trace_Op_Br0   : constant Unsigned_8 := 16#01#; -- Branch 0 taken at pc
   Trace_Op_Br1   : constant Unsigned_8 := 16#02#;
   Trace_Op_Br2   : constant Unsigned_8 := 16#04#;
   Trace_Op_Br3   : constant Unsigned_8 := 16#08#;

end Qemu_Traces;
