------------------------------------------------------------------------------
--                                                                          --
--                              Couverture                                  --
--                                                                          --
--                        Copyright (C) 2008, AdaCore                       --
--                                                                          --
-- Couverture is free software; you can redistribute it  and/or modify it   --
-- under terms of the GNU General Public License as published by the Free   --
-- Software Foundation; either version 2, or (at your option) any later     --
-- version.  Couverture is distributed in the hope that it will be useful,  --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-  --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License  for more details. You  should  have  received a copy of the GNU --
-- General Public License  distributed with GNAT; see file COPYING. If not, --
-- write  to  the Free  Software  Foundation,  59 Temple Place - Suite 330, --
-- Boston, MA 02111-1307, USA.                                              --
--                                                                          --
------------------------------------------------------------------------------
with Interfaces; use Interfaces;

package Qemu_Traces is
   --  Ada declaration of trace_header.
   --  See qemu-traces.h for the reference.
   type Trace_Header is record
      --  Magic string.
      Magic : String (1 .. 12);

      --  File version.
      Version : Unsigned_8;

      --  File kind.
      Kind : Unsigned_8;

      --  Size (in bytes) of the PC (program counter) of the target.
      Sizeof_Target_Pc : Unsigned_8;

      --  True if the host is big endian.
      Big_Endian : Unsigned_8;

      --  Target machine in big endian (uses ELF values).
      Machine_Hi : Unsigned_8;
      Machine_Lo : Unsigned_8;

      --  Pad (should be set to 0).
      Padding : Unsigned_16;
   end record;

   --  Expected value of the Magic field.
   Qemu_Trace_Magic : constant String := "#QEMU-Traces";

   --  Current version.
   Qemu_Trace_Version : constant Unsigned_8 := 1;

   --  Raw and history files are the one generated by Qemu.
   Qemu_Trace_Kind_Raw : constant Unsigned_8 := 0;
   Qemu_Trace_Kind_History : constant Unsigned_8 := 1;

   --  Consolidated files are generated by a post processing tool.
   --  (The number will be definitely set when the format is stable).
   Qemu_Trace_Kind_Consolidated : constant Unsigned_8 := 248;

   --  If the file kind is Consolidated the common header is followed by this
   --  additional header.
   --  This header may be followed by 1 to 3 bytes of pads so that the traces
   --  are aligned on 4 bytes.
   type Trace_Header_Consolidated is record
      --  Length of meta-data (using host endianness).
      --  Meta-data are just a raw stream of bytes (human readable text
      --  is expected).
      Length : Unsigned_32;
   end record;

   type Trace_Entry64 is record
      Pc : Unsigned_64;
      Size : Unsigned_16;
      Op : Unsigned_8;
      Pad0 : Unsigned_8;
      Pad1 : Unsigned_32;
   end record;

   type Trace_Entry32 is record
      Pc : Unsigned_32;
      Size : Unsigned_16;
      Op : Unsigned_8;
      Pad0 : Unsigned_8;
   end record;

   --  _BLOCK means pc .. pc+size-1 was executed.
   Trace_Op_Block : constant Unsigned_8 := 16#10#;
   Trace_Op_Fault : constant Unsigned_8 := 16#20#;
   Trace_Op_Br0   : constant Unsigned_8 := 16#01#; -- Branch 0 taken at pc
   Trace_Op_Br1   : constant Unsigned_8 := 16#02#;
   Trace_Op_Br2   : constant Unsigned_8 := 16#04#;
   Trace_Op_Br3   : constant Unsigned_8 := 16#08#;

end Qemu_Traces;
