# This is a example demonstrating branch coverage on a source featuring a
# decision with 3 conditions. The topology of the decision is such that we can
# achieve branch coverage with 3 tests only, while mcdc would require 4.

TESTS=test_clear_step test_pit_step test_rock_wait
XCOVLEVEL=branch
CONSOLIDATE=traces

include ../support/Makefile.examples
