[mypy]
# Ensure mypy works with namespace in which there is no toplevel
# __init__.py. Explicit_package_bases means that that mypy_path
# will define which directory is the toplevel directory of the
# namespace.
mypy_path = "$MYPY_CONFIG_FILE_DIR/testsuite/"
namespace_packages = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true

[mypy-SUITE.qdata]
disallow_untyped_defs = false
disallow_incomplete_defs = false
[mypy-SUITE.tgen]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[mypy-lxml.*]
ignore_missing_imports = true
