# This example features both an interactive program and a set of AUnit based
# tests for some of the program units. This Makefile lets you select the
# variant to exercise:

# make TESTS=explore            runs the interactive program
# make AUNIT_TESTS=test_explore  runs the AUnit based tests

# The interactive version of this test will only run in specially
# equipped configurations:

# make TARGET=powerpc-eabispe  ... runs on bare board PowerPC/e500v2

include ../support/Makefile.examples
