# This example features both an interactive program and a set of AUnit based
# tests for some of the program units. This Makefile lets you select the
# variant to exercise:

# make TESTS=explore            runs the interactive program
# make UNIT_TESTS=test_explore  runs the AUnit based tests

# Additionally, this Makefile lets you select target to use:

# make TARGET=native XCOVTARGET=i386-linux ... runs on x86-linux
# make TARGET=powerpc-elf                  ... runs on bare board PowerPC
# make TARGET=leon-elf                     ... runs on bare board Leon.

include ../support/Makefile.examples
