# To run this example, there are two options: use
#
# $ make TESTS=explore
#
# to run the explore example, and use it interactively, or
#
# $ make UNIT_TESTS=test_explore
#
# to run the AUnit based unit testing of the explore example
# in this case, AUnit needs to be installed for powerpc-elf.
include ../support/Makefile.examples
