------------------------------------------------------------------------------
--                                                                          --
--                               GNATcoverage                               --
--                                                                          --
--                        Copyright (C) 2026, AdaCore                       --
--                                                                          --
-- GNATcoverage is free software; you can redistribute it and/or modify it  --
-- under terms of the GNU General Public License as published by the  Free  --
-- Software  Foundation;  either version 3,  or (at your option) any later  --
-- version. This software is distributed in the hope that it will be useful --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License for  more details.  You should have  received  a copy of the GNU --
-- General  Public  License  distributed  with  this  software;   see  file --
-- COPYING3.  If not, go to http://www.gnu.org/licenses for a complete copy --
-- of the license.                                                          --
------------------------------------------------------------------------------

--  Unit implementing the source instrumentation action. This action derives
--  from GPR2.Build.Actions.Object.

with Ada.Containers.Hashed_Sets;

with GPR2.Build.Artifacts.Files;
with GPR2.Build.Command_Line;
with GPR2.Project.View;

with Instrument;
with Instrument.Common; use Instrument.Common;
with Switches;          use Switches;
with Strings;           use Strings;

package GPR2.Build.Actions.Instrument_Source is

   --  See the documentation in GPR2.Build.Actions for overriding subprograms

   type Instrument_Id (<>) is new GPR2.Build.Actions.Action_Id with private;

   type Object is new GPR2.Build.Actions.Object with private;

   overriding
   function UID (Self : Object) return Actions.Action_Id'Class;

   procedure Initialize
     (Self         : in out Object;
      LU_Info      : Library_Unit_Info;
      IC           : Inst_Context_Acc;
      Instrumenter : Instrument.Common.Language_Instrumenter_Acc;
      Prj_Info     : Project_Info_Access;
      Dump_Config  : Any_Dump_Config);
   --  Initialize a source instrumentation action

   overriding
   procedure Compute_Signature
     (Self : in out Object; Check_Checksums : Boolean);
   --  The signature compute inputs and outputs for the given unit
   --  instrumentation action.
   --
   --  The inputs are the source file, its dependencies, and the files
   --  instrumented in the context of this unit instrumentation action.
   --
   --  The outputs are the instrumentation artifacts resulting from the
   --  source instrumentation command.

   overriding
   procedure Compute_Command
     (Self           : in out Object;
      Slot           : Positive;
      Cmd_Line       : in out GPR2.Build.Command_Line.Object;
      Signature_Only : Boolean);
   --  Compute the command for the given source instrumentation action

   overriding
   function On_Tree_Insertion
     (Self : Object; Db : in out GPR2.Build.Tree_Db.Object) return Boolean;
   --  The On_Tree_Insertion primitive enables the action to insert its input
   --  and output artifacts, or any follow up action in the database so that
   --  the process scheduler execute actions in the right order. As the source
   --  instrumentation process is streamlined (one action for every
   --  instrumented sources), there is no need to take care of this. Thus this
   --  function has a dummy implementation that returns True.

   overriding
   function Post_Command
     (Self   : in out Object;
      Status : Execution_Status;
      Stdout : US.Unbounded_String := US.Null_Unbounded_String;
      Stderr : US.Unbounded_String := US.Null_Unbounded_String) return Boolean;
   --  Copy the SID file generated by the source instrumentation action to the
   --  library directory if needed.

   function Dependencies (Self : in out Object) return Containers.Filename_Set;
   --  Return the file dependencies for the instrument source action

   overriding
   function Extended (Self : Object) return Object
   is (raise Internal_Error with "This action is not extending");
   --  Do not handle project extension for now: always reinstrument even if
   --  the source was instrumented in an extended project.

   overriding
   function Execute
     (Self   : in out Object;
      Stdout : in out US.Unbounded_String;
      Stderr : in out US.Unbounded_String) return Integer;
   --  Execute the Instrument Source action in the current thread

   overriding
   function View (Self : Object) return GPR2.Project.View.Object;
   --  Return the view for the given source instrumentation action

   overriding
   function Working_Directory (Self : Object) return Path_Name.Object;
   --  Return the working directory for the given source instrumentation
   --  action.

   procedure Write_Instrumented_Files_List (Self : in out Object);
   --  Write the list of files instrumented in the context of this source
   --  instrumentation action. This shall consist of the main source file
   --  (Self.Src), but also of any header / unit part that is also of
   --  interest.
   --
   --  Take the following scenario: consider a project containing a pkg.c file,
   --  including a pkg.h header. The user instruments it and excludes pkg.h
   --  from coverage analysis. Then, it runs the instrumentation a second time,
   --  now including pkg.h: gnatcov thus needs to reinstrument pkg.c. In the
   --  first instrumentation, the instrumented dep file would contain only
   --  pkg.c, and in the second, it shall contain both pkg.c and pkg.h.

private
   type Instrument_Id (Name_Len : Natural) is new GPR2.Build.Actions.Action_Id
   with record
      Lang     : Language_Id;
      Ctxt     : GPR2.Project.View.Object;
      Src_Name : Simple_Name (1 .. Name_Len);
   end record;

   overriding
   function View (Self : Instrument_Id) return Project.View.Object
   is (Self.Ctxt);

   overriding
   function Action_Class (Self : Instrument_Id) return Value_Type
   is ("Instrument");

   overriding
   function Language (Self : Instrument_Id) return Language_Id
   is (Self.Lang);

   overriding
   function Action_Parameter (Self : Instrument_Id) return Value_Type
   is (Value_Type (Self.Src_Name));

   function Hash
     (Art : GPR2.Build.Artifacts.Files.Object) return Ada.Containers.Hash_Type
   is (Art.Hash);

   package Artifact_Sets is new
     Ada.Containers.Hashed_Sets
       (Element_Type        => GPR2.Build.Artifacts.Files.Object,
        Hash                => Hash,
        Equivalent_Elements => GPR2.Build.Artifacts.Files."=",
        "="                 => GPR2.Build.Artifacts.Files."=");

   type Object is new GPR2.Build.Actions.Object with record
      Deps_Cache : GPR2.Containers.Filename_Set;
      --  Cache for dependencies, to avoid recomputing them several times

      IC : Inst_Context_Acc;
      --  Instrumentation context

      Instrumenter : Instrument.Common.Language_Instrumenter_Acc;
      --  Instrumenter to use when instrumenting the source

      Prj_Info : Project_Info_Access;
      --  Project info for the unit to instrument

      Dump_Config : Any_Dump_Config;
      --  Dump config to pass to main instrumentation if this is also a main

      LU_Info : Library_Unit_Info;
      --  Instrumentation information for the compilation unit

      Artifacts : Artifact_Sets.Set;
      --  Artifacts for this source instrumentation action. This varies
      --  according to whether this is a unit of interest / a main.

   end record;

   function Unit_Name (Self : Object) return String;
   --  Return the unit to instrument as a source.
   --
   --  For Ada, this would be the unit name.
   --
   --  For C/C++, it is the full name to the original source when it has not
   --  been processed for manual / external annotations replacement priorly.
   --  Otherwise, it is the instrumented version of the source.

   function SID_Path (Self : Object) return GPR2.Path_Name.Object
   is (GPR2.Path_Name.Create_File
         (GPR2.Filename_Type
            (SID_Filename
               (Self.LU_Info.Main_Part_Src, In_Library_Dir => False))));
   --  Return the path for the SID file for this unit instrumentation action

   function Dep_File (Self : Object) return GPR2.Path_Name.Object
   is (GPR2.Path_Name.Create
         (Instrument.Common.Dependency_File
            (Self.Prj_Info.Desc,
             Self.LU_Info.Main_Part_Src.Path_Name.Virtual_File)));
   --  Return the path for the dependency file for this unit instrumentation
   --  action.

   function Files_Instrumentation_Info_File
     (Self : Object) return GPR2.Path_Name.Object
   is (GPR2.Path_Name.Create
         (Instrument.Common.Files_Instrumentation_Info_File
            (Self.Prj_Info.Desc, Self.Unit_Name)));
   --  Return the path of the file containing instrumentation information for
   --  this unit instrumentation action.

   function View (Self : Object) return GPR2.Project.View.Object
   is (Self.Ctxt);

   overriding
   function Working_Directory (Self : Object) return Path_Name.Object
   is (Self.Ctxt.Object_Directory);

end GPR2.Build.Actions.Instrument_Source;
