------------------------------------------------------------------------------
--                                                                          --
--                               GNATcoverage                               --
--                                                                          --
--                     Copyright (C) 2008-2024, AdaCore                     --
--                                                                          --
-- GNATcoverage is free software; you can redistribute it and/or modify it  --
-- under terms of the GNU General Public License as published by the  Free  --
-- Software  Foundation;  either version 3,  or (at your option) any later  --
-- version. This software is distributed in the hope that it will be useful --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License for  more details.  You should have  received  a copy of the GNU --
-- General  Public  License  distributed  with  this  software;   see  file --
-- COPYING3.  If not, go to http://www.gnu.org/licenses for a complete copy --
-- of the license.                                                          --
------------------------------------------------------------------------------

with Ada.Directories; use Ada.Directories;

with GNATCOLL.VFS; use GNATCOLL.VFS;

with GPR2.Path_Name;
with GPR2.Project.View;

with Files_Handling;    use Files_Handling;
with Instrument.Common; use Instrument.Common;
with Outputs;           use Outputs;
with Project;           use Project;

procedure Instrument.Clean_Objdirs
  (IC                   : in out Inst_Context;
   Instrumented_Sources : Unit_Maps.Map;
   Preserve_Artifacts   : Boolean;
   Keep_Going           : Boolean := False)
is
   --  Delete instrumentation artifacts.
   --
   --  If Keep_Going if true, deletion errors are not fatal. This is necessary
   --  when performing the cleaning precisely because a fatal error has already
   --  occurred, and we are cleaning up object directories following it.

   use GPR2;

   Instr_Artifacts : File_Sets.Set;
   --  List of instrumentation artifacts (SID files, instrumented files) that
   --  will be generated by the current instrumentation run.

   procedure Clean_Subdir (Project : GPR2.Project.View.Object);
   --  Callback for Project.Iterate_Projects. If Project is not externally
   --  built, remove all files from the "$project_name-gnatcov-instr" folder in
   --  Project's object directory, and remove all files ending in ".sid" from
   --  the object and library directory, if applicable.

   function Has_Regular_Files
     (Directory : GNATCOLL.VFS.Virtual_File) return Boolean;
   --  Return whether Directory contains at least one regular file

   ------------------
   -- Clean_Subdir --
   ------------------

   procedure Clean_Subdir (Project : GPR2.Project.View.Object) is

      --  TODO??? revisit this when we properly deal with incrementality in
      --  extending projects. For now, clean every extended project to avoid
      --  leaving instrumentation artifacts there.

      Output_Dir     : constant GNATCOLL.VFS.Virtual_File :=
        Project_Output_Dir (Project, In_Extending => False);
      Has_Output_Dir : Boolean := True;
   begin
      Clean_Objdirs_Trace.Increase_Indent
        ("Processing " & String (Project.Name));
      Clean_Objdirs_Trace.Trace
        ("GPR file: " & String (Project.Path_Name.Value));

      --  Some projects don't have an object directory: ignore them as there is
      --  nothing to do.

      if Output_Dir = GNATCOLL.VFS.No_File then
         Has_Output_Dir := False;
         Clean_Objdirs_Trace.Trace ("no object directory");
      else
         Clean_Objdirs_Trace.Trace
           ("output directory: " & Output_Dir.Display_Full_Name);
         if not Exists (Output_Dir.Display_Full_Name) then
            Has_Output_Dir := False;
            Clean_Objdirs_Trace.Trace ("it does not exist");
         elsif not GNATCOLL.VFS.Is_Directory (Output_Dir) then
            Has_Output_Dir := False;
            Clean_Objdirs_Trace.Trace ("it is not a directory");
         end if;
      end if;

      if not Has_Output_Dir then
         Clean_Objdirs_Trace.Decrease_Indent;
         return;
      end if;

      --  Unless externally built project processing has been enabled, having
      --  instrumented sources in externally built projects is very suspicious
      --  and could easily trigger build errors later on.
      --
      --  For instance, if:
      --
      --  * project P depends on project Lib
      --  * Lib is instrumented
      --  * P is instrumented while Lib is tagged as externally built
      --
      --  then auto-dump code for P's main will not try to dump coverage
      --  buffers for Lib, and thus the link of P's main executable will fail
      --  because Lib's units refer to their coverage buffers, which are not
      --  included in the link.
      --
      --  To avoid confusion, warn about such cases now, so that users have a
      --  clear lead on how to address such problems.

      if Project.Is_Externally_Built then
         Clean_Objdirs_Trace.Trace ("it is an externally built project");

         if not Externally_Built_Projects_Processing_Enabled
           and then Has_Regular_Files (Output_Dir)
         then
            --  Short of re-implementing non trivial project handling logic,
            --  there is no API that allows us to determine whether files in
            --  Output_Dir would be considered as sources with --src-subdirs:
            --  consider that all files there could be sources.

            Warn
              ("Project """
               & String (Project.Name)
               & """ is externally"
               & " built and does not contain units of interest, however it"
               & " contains instrumented sources");
         end if;

         --  We should never try to modify externally built projects, so do not
         --  remove their instrumented source directory.

         Clean_Objdirs_Trace.Decrease_Indent;
         return;
      end if;

      --  Remove instrumented sources that are not instrumentation artifacts
      --  (e.g. generated by a previous instrumentation run, with an alternate
      --  set of switches).

      Clean_Dir
        (Output_Dir.Display_Full_Name,
         Pattern       => "",
         Ignored_Files => Instr_Artifacts,
         Keep_Going    => Keep_Going,
         Trace         => Clean_Objdirs_Trace);

      --  Also remove SID files that are not instrumentation artifacts

      if Project.Kind in GPR2.With_Object_Dir_Kind
        and then Project.Object_Directory.Exists
      then
         Clean_Dir
           (Project.Object_Directory.String_Value,
            Pattern       => "*.sid",
            Ignored_Files => Instr_Artifacts,
            Keep_Going    => Keep_Going,
            Trace         => Clean_Objdirs_Trace);
      end if;
      if Project.Kind in GPR2.Library_Kind
        and then Project.Library_Directory.Exists
      then
         Clean_Dir
           (Project.Library_Directory.String_Value,
            Pattern       => "*.sid",
            Ignored_Files => Instr_Artifacts,
            Keep_Going    => Keep_Going,
            Trace         => Clean_Objdirs_Trace);
      end if;

      Clean_Objdirs_Trace.Decrease_Indent;
   end Clean_Subdir;

   -----------------------
   -- Has_Regular_Files --
   -----------------------

   function Has_Regular_Files
     (Directory : GNATCOLL.VFS.Virtual_File) return Boolean
   is
      S : Search_Type;
   begin
      return Result : Boolean do
         Start_Search
           (Search    => S,
            Directory => Directory.Display_Full_Name,
            Pattern   => "",
            Filter    => (Ordinary_File => True, others => False));
         Result := More_Entries (S);
         End_Search (S);
      end return;
   end Has_Regular_Files;

   --  Start of processing for Instrument.Clean_Objdirs

begin
   --  Compute the list of artifacts generated by the instrumentation process.
   --  Remove every other coverage artifact.

   if Preserve_Artifacts then
      for LU_Info of Instrumented_Sources loop

         --  Start with SID files: gnatcov generates one in the object
         --  directory, and in the library directory if there is one.

         declare
            Obj_SID : constant String :=
              SID_Filename (LU_Info.Main_Part_Src, In_Library_Dir => False);
            Lib_SID : constant String :=
              SID_Filename (LU_Info.Main_Part_Src, In_Library_Dir => True);
         begin
            if LU_Info.Is_UOI then
               Instr_Artifacts.Insert (Create (+Obj_SID));
               if Lib_SID /= "" and then Obj_SID /= Lib_SID then
                  Instr_Artifacts.Insert (Create (+Lib_SID));
               end if;
            end if;
         end;

         --  Then, gather the instrumentation artifacts that should be
         --  preserved, for incrementality purposes.

         declare
            Src : constant GPR2.Build.Source.Object := LU_Info.Main_Part_Src;
            Prj : Prj_Desc renames
              Get_Or_Create_Project_Info (IC, LU_Info.Instr_Project).Desc;
         begin
            Instr_Artifacts.Union
              (Instrumentation_Artifacts (Main_Part_Src => Src, Prj => Prj));
         end;
      end loop;

      --  Cleanup temporary artifacts if not instructed to keep them

      if Save_Temps then
         Instr_Artifacts.Insert (Create (+(+IC.Mapping_File)));
         Instr_Artifacts.Insert (Create (+(+IC.Config_Pragmas_Mapping)));
         Instr_Artifacts.Insert
           (Create (+(+IC.Sources_Of_Interest_Response_File)));
         Instr_Artifacts.Insert (Create (+(+IC.Ada_Preprocessor_Data_File)));
      end if;

      --  Trace the preserved artifacts

      Clean_Objdirs_Trace.Increase_Indent
        ("Preserving instrumentation artifacts:");
      for Art of Instr_Artifacts loop
         Clean_Objdirs_Trace.Trace (Art.Display_Full_Name);
      end loop;
      Clean_Objdirs_Trace.Decrease_Indent;
   end if;

   --  Go through all projects to clear up their object directories. Also go
   --  through extended projects, as their object directories can interfere
   --  with the build of the extending project.

   Iterate_Projects
     (Root_Project             => Project.Project.Root_Project,
      Process                  => Clean_Subdir'Access,
      Recursive                => True,
      Include_Extended         => True,
      Include_Externally_Built => True);
end Instrument.Clean_Objdirs;
