------------------------------------------------------------------------------
--                                                                          --
--                               GNATcoverage                               --
--                                                                          --
--                        Copyright (C) 2026, AdaCore                       --
--                                                                          --
-- GNATcoverage is free software; you can redistribute it and/or modify it  --
-- under terms of the GNU General Public License as published by the  Free  --
-- Software  Foundation;  either version 3,  or (at your option) any later  --
-- version. This software is distributed in the hope that it will be useful --
-- but WITHOUT ANY WARRANTY;  without even the implied warranty of MERCHAN- --
-- TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public --
-- License for  more details.  You should have  received  a copy of the GNU --
-- General  Public  License  distributed  with  this  software;   see  file --
-- COPYING3.  If not, go to http://www.gnu.org/licenses for a complete copy --
-- of the license.                                                          --
------------------------------------------------------------------------------

with GPR2.Build.Actions.Process;
with GPR2.Build.Tree_Db;

package Instrument.Actions.Instrument_Source.Process is

   type Object is new GPR2.Build.Actions.Process.Object with record
      Instrument_Object : Instrument.Actions.Instrument_Source.Object_Acc;
   end record;

   procedure Initialize
     (Self         : in out Object;
      LU_Info      : Library_Unit_Info;
      IC           : Inst_Context_Acc;
      Instrumenter : Instrument.Common.Language_Instrumenter_Acc;
      Prj_Info     : Project_Info_Access;
      Dump_Config  : Any_Dump_Config);

   overriding
   procedure Compute_Signature
     (Self : in out Object; Check_Checksums : Boolean);
   --  Compute inputs and outputs for the given unit
   --  instrumentation action.
   --
   --  The inputs are the source file, its dependencies, and the files
   --  instrumented in the context of this unit instrumentation action.
   --
   --  The outputs are the instrumentation artifacts resulting from the
   --  source instrumentation command.

   procedure Compute_Command
     (Self           : in out Object;
      Slot           : Positive;
      Cmd_Line       : in out GPR2.Build.Command_Line.Object;
      Signature_Only : Boolean);
   --  Compute the command for the given source instrumentation action

   overriding
   function On_Tree_Insertion
     (Self : Object; Db : in out GPR2.Build.Tree_Db.Object) return Boolean;
   --  The On_Tree_Insertion primitive enables the action to insert its input
   --  and output artifacts, or any follow up action in the database so that
   --  the process scheduler execute actions in the right order. As the source
   --  instrumentation process is streamlined (one action for every
   --  instrumented sources), there is no need to take care of this. Thus this
   --  function has a dummy implementation that returns True.

   overriding
   function Post_Execution
     (Self   : in out Object;
      Status : GPR2.Build.Actions.Execution_Status;
      Stdout : US.Unbounded_String := US.Null_Unbounded_String;
      Stderr : US.Unbounded_String := US.Null_Unbounded_String) return Boolean;
   --  Copy the SID file generated by the source instrumentation action to the
   --  library directory if needed.

   overriding
   function Extended (Self : Object) return Object
   is (raise Internal_Error with "This action is not extending");
   --  Do not handle project extension for now: always reinstrument even if
   --  the source was instrumented in an extended project.

   overriding
   function Working_Directory (Self : Object) return Path_Name.Object;

   overriding
   function UID (Self : Object) return GPR2.Build.Actions.Action_Id'Class
   is (Self.Instrument_Object.UID);

private
   overriding
   function Working_Directory (Self : Object) return Path_Name.Object
   is (Self.View.Object_Directory);
end Instrument.Actions.Instrument_Source.Process;
