"""
Ensure that gnatcov loads switches from the project designated by the
Origin_Project attribute, and not from any extending project. This is required
for the gnattest-gnatcov integration to work properly, as gnattest
systematically generates an extending project of the user project when stubbing
is enabled.

The sources in the code and test directories are made to mimic the structure of
the harnesses generated by gnattest
"""

from e3.fs import cp

from SCOV.minicheck import build_run_and_coverage, check_xcov_reports
from SUITE.context import thistest
from SUITE.cutils import Wdir
from SUITE.gprutils import GPRswitches
from SUITE.tutils import gprfor


tmp = Wdir("tmp_")

# Copy the test material in the temp dir
cp("../test", ".", recursive=True)
cp("../code", ".", recursive=True)

# Generate a project for the test driver, "withing" the stub project and
# referencing the user project through the Origin_Project attribute
test_prj = gprfor(
    mains=["pkg-test.adb"],
    prjid="test",
    srcdirs="test",
    deps=["code/stubs.gpr"],
    extra='for Origin_Project use "code/user.gpr";',
)

# No level or annotation format provided, everything should be loaded from
# the Origin_Project (user.gpr).
build_run_and_coverage(
    gprsw=GPRswitches(root_project=test_prj),
    covlevel=None,
    extra_coverage_args=[],
    mains=["pkg-test"],
)

check_xcov_reports(
    "xcov",
    {
        "pkg.ads.xcov": {},
        "pkg.adb.xcov": {"!": {7}, "+": {8}, "-": {10}},
    },
)

thistest.result()
