# This is a simple "Hello World" example. This Makefile lets you select
# target to use:

# make TARGET=i386-linux   runs on linux
# make TARGET=powerpc-elf  runs on bare board PowerPC
# make TARGET=leon-elf     runs on bare board LEON2

TESTS=hello
include ../support/Makefile.examples
