# This is a simple "Hello World" example. This Makefile lets you select
# target to use:

# make TARGET=native XCOVTARGET=i386-linux ... runs on x86-linux
# make TARGET=powerpc-elf                  ... runs on bare board PowerPC
# make TARGET=leon-elf                     ... runs on bare board Leon.

TESTS=hello
include ../support/Makefile.examples
