# This is a example of code with an and-then decision.

# 3 individual tests exercise variants of True/False on the conditions, all
# leading to incomplete decision coverage.  Consolidation yields mcdc
# coverage. Request consolidation with checkpoints, just to illustrate how the
# process goes.

TESTS=test_stable test_unstable_p test_unstable_t
XCOVLEVEL=stmt+mcdc
CONSOLIDATE=checkpoints

include ../support/Makefile.examples
